# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Authkeeper < Formula
  desc "A secure CLI secret manager and OAuth2/OIDC client"
  homepage "https://github.com/ksysoev/authkeeper"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ksysoev/authkeeper/releases/download/v0.0.2/authkeeper_Darwin_x86_64.tar.gz"
      sha256 "95b196604a780be5af27707a178da922a286c1f319e1ca5dbce6f19233c6c856"

      def install
        bin.install 'authkeeper'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ksysoev/authkeeper/releases/download/v0.0.2/authkeeper_Darwin_arm64.tar.gz"
      sha256 "6d3138718ab3a4b922f0b936085dad240a7a61da95eac57921e31e52c32e04e1"

      def install
        bin.install 'authkeeper'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ksysoev/authkeeper/releases/download/v0.0.2/authkeeper_Linux_x86_64.tar.gz"
      sha256 "dd0a631e3d8f8ec35e1ca9c1bcfa4d8827f258661875c71dc8b611885b304d01"
      def install
        bin.install 'authkeeper'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ksysoev/authkeeper/releases/download/v0.0.2/authkeeper_Linux_arm64.tar.gz"
      sha256 "7e695d584ed95367822d98101222063c792d3a69a14a4a0f076d0b781128411a"
      def install
        bin.install 'authkeeper'
      end
    end
  end

  test do
    system "#{bin}/authkeeper", "--version"
  end
end
