# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Authkeeper < Formula
  desc "A secure CLI secret manager and OAuth2/OIDC client"
  homepage "https://github.com/ksysoev/authkeeper"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ksysoev/authkeeper/releases/download/v0.0.1/authkeeper_Darwin_x86_64.tar.gz"
      sha256 "89ce202f521214e23b15cc59262a4d528edc0ecf6085a1b91636d09c4fce1480"

      def install
        bin.install 'authkeeper'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ksysoev/authkeeper/releases/download/v0.0.1/authkeeper_Darwin_arm64.tar.gz"
      sha256 "26722295559d9612a1a72ee00f1983e0f58b0d6028f16254f1dfbaac11854f47"

      def install
        bin.install 'authkeeper'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ksysoev/authkeeper/releases/download/v0.0.1/authkeeper_Linux_x86_64.tar.gz"
      sha256 "0cbd5473467ee1e07652f541892226fd4f789ff94ebfaacb68314ad3e966cecf"
      def install
        bin.install 'authkeeper'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ksysoev/authkeeper/releases/download/v0.0.1/authkeeper_Linux_arm64.tar.gz"
      sha256 "d1e287d022466feaecd1759abdbe28ef86d32461dfb7ba56b5f093a54bbe21be"
      def install
        bin.install 'authkeeper'
      end
    end
  end

  test do
    system "#{bin}/authkeeper", "--version"
  end
end
